version: '3.7'

services:
  mysqldb:
    image: mysql:8.0.27
    container_name: POS_MySQL_Authentication
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql